const stations = [
  { "id": 1, "location": "Mumbai", "railwayStation": "Chhatrapati Shivaji Terminus (CST)" },
  { "id": 2, "location": "Delhi", "railwayStation": "New Delhi Railway Station (NDLS)" },
  { "id": 3, "location": "Bangalore", "railwayStation": "Bangalore City Railway Station (SBC)" },
  { "id": 4, "location": "Chennai", "railwayStation": "Chennai Central Railway Station (MAS)" },
  { "id": 5, "location": "Hyderabad", "railwayStation": "Hyderabad Deccan Railway Station (HYB)" },
  { "id": 6, "location": "Kolkata", "railwayStation": "Howrah Junction Railway Station (HWH)" },
  { "id": 7, "location": "Pune", "railwayStation": "Pune Junction Railway Station (PUNE)" },
  { "id": 8, "location": "Ahmedabad", "railwayStation": "Ahmedabad Junction Railway Station (ADI)" },
  { "id": 9, "location": "Jaipur", "railwayStation": "Jaipur Junction Railway Station (JP)" },
  { "id": 10, "location": "Lucknow", "railwayStation": "Lucknow Charbagh Railway Station (LKO)" },
  { "id": 11, "location": "Kochi", "railwayStation": "Ernakulam Junction Railway Station (ERS)" },
  { "id": 12, "location": "Goa", "railwayStation": "Madgaon Junction Railway Station (MAO)" },
  { "id": 13, "location": "Amritsar", "railwayStation": "Amritsar Junction Railway Station (ASR)" },
  { "id": 14, "location": "Bhubaneswar", "railwayStation": "Bhubaneswar Railway Station (BBS)" },
  { "id": 15, "location": "Coimbatore", "railwayStation": "Coimbatore Junction Railway Station (CBE)" },
  { "id": 16, "location": "Trivandrum", "railwayStation": "Trivandrum Central Railway Station (TVC)" },
  { "id": 17, "location": "Nagpur", "railwayStation": "Nagpur Junction Railway Station (NGP)" },
  { "id": 18, "location": "Indore", "railwayStation": "Indore Junction Railway Station (INDB)" },
  { "id": 19, "location": "Bhopal", "railwayStation": "Bhopal Junction Railway Station (BPL)" },
  { "id": 20, "location": "Vadodara", "railwayStation": "Vadodara Junction Railway Station (BRC)" },
  { "id": 21, "location": "Agra", "railwayStation": "Agra Cantt Railway Station (AGC)" },
  { "id": 22, "location": "Bagdogra", "railwayStation": "New Jalpaiguri Junction Railway Station (NJP)" },
  { "id": 23, "location": "Jaipur", "railwayStation": "Gandhinagar Jaipur Railway Station (GADJ)" },
  { "id": 24, "location": "Lucknow", "railwayStation": "Lucknow Junction Railway Station (LJN)" },
  { "id": 25, "location": "Kochi", "railwayStation": "Kochi Harbour Terminus (KCHT)" },
  { "id": 26, "location": "Goa", "railwayStation": "Karmali Railway Station (KRMI)" },
  { "id": 27, "location": "Amritsar", "railwayStation": "Amritsar Junction Railway Station (ASR)" },
  { "id": 28, "location": "Bhubaneswar", "railwayStation": "Bhubaneswar New Railway Station (BBSN)" },
  { "id": 29, "location": "Coimbatore", "railwayStation": "Coimbatore North Junction Railway Station (CBF)" },
  { "id": 30, "location": "Trivandrum", "railwayStation": "Kochuveli Railway Station (KCVL)" },
  { "id": 31, "location": "Nagpur", "railwayStation": "Ajni Railway Station (AJNI)" },
  { "id": 32, "location": "Indore", "railwayStation": "Lakshmibai Nagar Railway Station (LMNR)" },
  { "id": 33, "location": "Bhopal", "railwayStation": "Habibganj Railway Station (HBJ)" },
  { "id": 34, "location": "Vadodara", "railwayStation": "Vadodara Junction Railway Station (BRC)" },
  { "id": 35, "location": "Agra", "railwayStation": "Agra Fort Railway Station (AF)" },
  { "id": 36, "location": "Bagdogra", "railwayStation": "Bagdogra Railway Station (BDRA)" },
  { "id": 37, "location": "Varanasi", "railwayStation": "Varanasi Junction Railway Station (BSB)" },
  { "id": 38, "location": "Patna", "railwayStation": "Patna Junction Railway Station (PNBE)" },
  { "id": 39, "location": "Ranchi", "railwayStation": "Ranchi Junction Railway Station (RNC)" },
  { "id": 40, "location": "Guwahati", "railwayStation": "Guwahati Railway Station (GHY)" },
  { "id": 41, "location": "Chandigarh", "railwayStation": "Chandigarh Junction Railway Station (CDG)" },
  { "id": 42, "location": "Jaipur", "railwayStation": "Bais Godam Railway Station (BGDM)" },
];
module.exports = { stations };
